version: '3.8'

services:
  backend:
    image: dhruv1345/vc-app-backend:latest
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: dhruv1345/vc-app-frontend:latest
    ports:
      - "3000:3000"
    restart: always
